/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inscriptionetudiants;

import static inscriptionetudiants.ConnexionBD.connexion;
import static inscriptionetudiants.InscriptionEtudiants.con;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class EnregistrementEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form EnregistrementEtudiant
     */
   // Connection con = (Connection)connexion();
    Statement st=null;
    ResultSet rst=null;
    PreparedStatement pst=null;
    
    public EnregistrementEtudiant() {
        initComponents();
        show_Etudiant();
    }
    
   public String inscrireEtudiant(String email){ 
    
     return email;     
    }
             
   public String inscrireEtudiantcni(String cni){ 
    
     return cni;     
    }
   
   public String inscrireEtudiantmatricule(String matricule){ 
    
     return matricule;     
    }
   
   public String inscrireEtudiantnom(String nom){ 
    
     return nom;     
    }
   
   public String inscrireEtudiantprenom(String prenom){ 
    
     return prenom;     
    }
   
   public String inscrireEtudiantfiliere(String filiere){ 
    
     return filiere;     
    }
   
   public String inscrireEtudiantniveau(String niveau){ 
    
     return niveau;     
    }
   
   public int inscrireEtudiantage(int age){ 
    
     return age;     
    }
  /*  
   String inscrireEtudiant(String email, String cni, String matricule,String nom,String prenom,String filiere, String niveau, int age){ 
     System.out.printf(email, cni, matricule, nom, prenom, filiere, niveau, age);
    // return email, cni, matricule, nom, prenom, filiere, niveau, age;
 //   String lister = "email"+"cni"+"matricule"+"nom"+"prenom"+"filiere"+"niveau"+age;
    String lister = "email"+"cni"+"matricule"+"nom"+"prenom"+"filiere"+"niveau"+age;
     return lister;
 //   return "email"+"cni"+"matricule"+"nom"+"prenom"+"filiere"+"niveau"+age;
 
        
    } */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        nomfield = new javax.swing.JTextField();
        prenomfield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        matriculefield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cnifield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        filierefield = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        niveaufield = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("                     INSCRIPTION ETUDIANTS");

        jLabel2.setText("Nom");

        jLabel3.setText("Age");

        jLabel4.setText("Prenom");

        valider.setBackground(new java.awt.Color(0, 153, 0));
        valider.setText("AJOUTER");
        valider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(204, 0, 0));
        annuler.setText("ANNULER");
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        nomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfieldActionPerformed(evt);
            }
        });

        prenomfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomfieldActionPerformed(evt);
            }
        });

        agefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agefieldActionPerformed(evt);
            }
        });

        matriculefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculefieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Matricule");

        jLabel8.setText("Cni");

        cnifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnifieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Email");

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Filiere");

        filierefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "informatique", "physique", "mathematique", "chimie", "biologie", "geologie" }));
        filierefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filierefieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Niveau");

        niveaufield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "M1", "M2", "D1", "D2", "D3" }));

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Age", "Cni", "Email", "Matricule", "Filiere", "Niveau"
            }
        ));
        jScrollPane1.setViewportView(tableau);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(78, 78, 78)
                                        .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prenomfield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cnifield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailfield)
                                    .addComponent(matriculefield)
                                    .addComponent(filierefield, 0, 235, Short.MAX_VALUE)
                                    .addComponent(niveaufield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(nomfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenomfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cnifield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(matriculefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(filierefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(niveaufield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomfieldActionPerformed
     //    String prenom = prenomfield.getText().toString(); 
    }//GEN-LAST:event_prenomfieldActionPerformed
    public ArrayList<Etudiant> etudList() {
        ArrayList<Etudiant> etudList = new ArrayList<>();

        try {
            con = (com.mysql.jdbc.Connection) connexion();
            String query = "SELECT * FROM etudiant";
            st=con.createStatement();
            rst = st.executeQuery(query);
            Etudiant etud;
            while(rst.next()){
                etud=new Etudiant(rst.getString("email"), rst.getString("cni"), rst.getString("matricule"), rst.getString("nom"), rst.getString("prenom"),  rst.getString("filiere"), rst.getString("niveau"), rst.getInt("age"));
                    etudList.add(etud);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EnregistrementEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        return etudList;
   }
   public void show_Etudiant(){
    ArrayList<Etudiant> list = etudList();
    DefaultTableModel model = (DefaultTableModel)tableau.getModel();
    Object[] row = new Object[8];
    for(int i=0; i<list.size(); i++){
        row[0]=list.get(i).getNom();
        row[1]=list.get(i).getPrenom();
        row[2]=list.get(i).getAge();
        row[3]=list.get(i).getCni();
        row[4]=list.get(i).getEmail();
        row[5]=list.get(i).getMatricule();
        row[6]=list.get(i).getFiliere();
        row[7]=list.get(i).getNiveau();
        model.addRow(row);
        
    }
   }
    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        String email = emailfield.getText();                                               
        String cni = cnifield.getText();                                           
        String matricule = matriculefield.getText();                                       
        String nom = nomfield.getText();
        String prenom = prenomfield.getText(); 
        Integer age =Integer.parseInt(agefield.getText());
        String filiere = niveaufield.getSelectedItem().toString();
        String niveau = filierefield.getSelectedItem().toString();
                                                    
      
        
        String query ="INSERT INTO etudiant (email, cni, matricule, nom, prenom, age, filiere, niveau) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try{
           
           con = (com.mysql.jdbc.Connection) connexion();
           st=con.createStatement();
           
           
           if(!email.equals("") &&!cni.equals("") &&!matricule.equals("") && !nom.equals("") && !prenom.equals("") && !age.equals("") && !filiere.equals("") && !niveau.equals("")){
            pst=con.prepareStatement(query);
            pst.setString(1, email);
            pst.setString(2, cni);
            pst.setString(3, matricule); 
            pst.setString(4, nom);
            pst.setString(5, prenom);
            pst.setInt(6, age);
            pst.setString(7, filiere);
            pst.setString(8, niveau);
        
           pst.executeUpdate(); 
           
           emailfield.setText("");
           cnifield.setText("");
           matriculefield.setText("");
           nomfield.setText("");
           prenomfield.setText("");
           agefield.setText("");
           niveaufield.setSelectedIndex(0);
           filierefield.setSelectedIndex(0);
           DefaultTableModel model = (DefaultTableModel)tableau.getModel();
           Object[] row = new Object[8];
            row[0]=nom;
            row[1]=prenom;
            row[2]=age;
            row[3]=cni;
            row[4]=email;
            row[5]=matricule;
            row[6]=filiere;
            row[7]=niveau;
            model.addRow(row);
          
           JOptionPane.showMessageDialog(null, "votre ajout a ete effectuée avec succes!!!");
            
        }else{
           JOptionPane.showMessageDialog(null, "votre ajout a ete effectuée avec succes!!!");
           }   
        }catch(SQLException e){
          System.out.println(e.getMessage());  
        }
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
      
           emailfield.setText("");
           cnifield.setText("");
           matriculefield.setText("");
           nomfield.setText("");
           prenomfield.setText("");
           agefield.setText("");
           niveaufield.setSelectedIndex(0);
           filierefield.setSelectedIndex(0);
        
    }//GEN-LAST:event_annulerActionPerformed

    private void nomfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfieldActionPerformed
     //   String nom = nomfield.getText().toString();
    }//GEN-LAST:event_nomfieldActionPerformed

    private void agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agefieldActionPerformed
   //     String age = agefield.getText();
    }//GEN-LAST:event_agefieldActionPerformed

    private void matriculefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculefieldActionPerformed
     //  String matricule = matriculefield.getText().toString();
    }//GEN-LAST:event_matriculefieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
    //    String email = emailfield.getText().toString();
    }//GEN-LAST:event_emailfieldActionPerformed

    private void cnifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnifieldActionPerformed
    //    String cni = cnifield.getText().toString();
    }//GEN-LAST:event_cnifieldActionPerformed

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_validerMouseClicked

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerMouseClicked

    private void filierefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filierefieldActionPerformed

    }//GEN-LAST:event_filierefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrementEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrementEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrementEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrementEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrementEtudiant().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField cnifield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JComboBox<String> filierefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matriculefield;
    private javax.swing.JComboBox<String> niveaufield;
    private javax.swing.JTextField nomfield;
    private javax.swing.JTextField prenomfield;
    private javax.swing.JTable tableau;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

 
}
